# Export CMS DB from Optimizely DXP Integration
trigger: none

variables:
- group: DXP-variables

pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-latest'

steps:
- checkout: none  # Don't sync sources

- task: DxpExportDb@2
  inputs:
    ClientKey: '$(ClientKey)'
    ClientSecret: '$(ClientSecret)'
    ProjectId: '$(DXP.ProjectId)'
    Environment: 'Integration'
    DatabaseName: 'epicms' #epicms|epicommerce
    RetentionHours: 24
    Timeout: 7200
