trigger: none

variables:
- group: DXP-variables

stages:

- stage: Reset
  jobs:
  - job: ResetIntegration
    pool:
      vmImage: 'ubuntu-latest'
    
    steps:
    
    - checkout: none  # Don't sync sources

    - task: DxpResetDeploy@2
      displayName: 'Reset DXP Integration environment'
      inputs:
        ClientKey: '$(ClientKey)'
        ClientSecret: '$(ClientSecret)'
        ProjectId: '$(DXP.ProjectId)'
        TargetEnvironment: 'Integration'
        Timeout: 1800
