trigger: none

variables:
- group: Episerver.com DXP-variables

stages:

- stage: Reset
  jobs:
  - job: ResetIntegration
    pool:
      vmImage: 'windows-latest'
    
    steps:
    
    - checkout: none  # Don't sync sources

    - task: DxpResetDeploy@1
      displayName: 'Reset Integration'
      inputs:
        ClientKey: '$(ClientKey)'
        ClientSecret: '$(ClientSecret)'
        ProjectId: '$(DXP.ProjectId)'
        TargetEnvironment: 'Integration'
        Timeout: 1800

  - job: ResetPreproduction
    dependsOn: ResetIntegration
    pool:
      vmImage: 'windows-latest'
    
    steps:

    - checkout: none  # Don't sync sources

    - task: DxpResetDeploy@1
      displayName: 'Reset Preproduction'
      inputs:
        ClientKey: '$(ClientKey)'
        ClientSecret: '$(ClientSecret)'
        ProjectId: '$(DXP.ProjectId)'
        TargetEnvironment: 'Preproduction'
        Timeout: 1800

  - job: ResetProduction
    dependsOn: ResetPreproduction
    pool:
      vmImage: 'windows-latest'
    
    steps:

    - checkout: none  # Don't sync sources

    - task: DxpResetDeploy@1
      displayName: 'Reset Production'
      inputs:
        ClientKey: '$(ClientKey)'
        ClientSecret: '$(ClientSecret)'
        ProjectId: '$(DXP.ProjectId)'
        TargetEnvironment: 'Production'
        Timeout: 1800