trigger: none

variables:
- group: DXP-variables

pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'

steps:
- checkout: none  # Don't sync sources

- task: DxpDeployTo@1
  inputs:
    ClientKey: '$(ClientKey)'
    ClientSecret: '$(ClientSecret)'
    ProjectId: '$(DXP.ProjectId)'
    SourceEnvironment: 'Preproduction'
    TargetEnvironment: 'Integration'
    SourceApp: 'commerce'
    UseMaintenancePage: false
    IncludeBlob: false
    IncludeDb: true
    Timeout: 3600

- task: DxpSmokeTestIfFailReset@1
  inputs:
    ClientKey: '$(ClientKey)'
    ClientSecret: '$(ClientSecret)'
    ProjectId: '$(DXP.ProjectId)'
    TargetEnvironment: 'Integration'
    Urls: '$(Integration.SlotUrl)$(UrlSuffix)'
    SleepBeforeStart: 20
    Timeout: 1800

- task: DxpCompleteDeploy@1
  inputs:
    ClientKey: '$(ClientKey)'
    ClientSecret: '$(ClientSecret)'
    ProjectId: '$(DXP.ProjectId)'
    TargetEnvironment: 'Integration'
    Timeout: 1800
