name: Test scripts

on:
  push:
    branches:
      - develop
      - feature/**
  pull_request:
  workflow_dispatch: # Allow manuel trigger of the workflow

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Get extension version
      #   shell: pwsh
      #   run: |
      #     $version = (Get-Content src/vss-extension.json) -join "`n" | ConvertFrom-Json | Select -ExpandProperty "version"
      #     $buildNumber = $env:GITHUB_RUN_NUMBER
      #     $extVersion = "v$version-$buildNumber"
      #     Write-Host "Try to set VERSION to $version"
      #     Add-Content -Path $env:GITHUB_ENV -Value "VERSION=$version"
      #     Write-Host "Try to set EXTENSION_VERSION to $extVersion"
      #     Add-Content -Path $env:GITHUB_ENV -Value "EXTENSION_VERSION=$extVersion"
      - uses: ./.github/actions/get-extension-version

      - name: Show VERSION/EXTENSION_VERSION
        run: 
          echo "VERSION=$VERSION"
          echo "EXTENSION_VERSION=$EXTENSION_VERSION"

      - uses: ./.github/actions/populate-psmodules-folders

      - uses: ./.github/actions/build-node-tasks

      - name: Rename tasks to TEST
        shell: pwsh
        run: |
          ./BuildScripts/RenameTasksToTest.ps1

      # - name: npm install
      #   run: npm install
      #   working-directory: ./src

      # - name: Install tfx-cli
      #   run: npm install -g tfx-cli@0.18.0

      # - name: Set extension filename variable
      #   run: echo "VsixFileName=epinova-dxp-deploy-extension-test-$EXTENSION_VERSION.vsix" >> $GITHUB_ENV

      # - name: Show VsixFileName
      #   run: echo "The value of VsixFileName is $VsixFileName"

      # - name: Package Extension
      #   run: tfx extension isvalid --root "src" --manifests "vss-extension.json" --outputPath $VsixFileName --json

